apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: node-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
    nodePort: 32000
  selector:
    app: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  template:
    metadata:
      name: node-helloworld
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodejs-private-reg-container
          image: bibincatchme/nodejs:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: imagereg      
  selector:
    matchLabels:
      app: nodeapp
