apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: node-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 32000
  selector:
    app: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: nodeapp
spec:
  serviceAccountName: jenkins
  replicas: 2
  template:
    metadata:
      name: node-helloworld
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodejs
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nodeapp
