apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: node-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 32000
  selector:
    app: nodeapp
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
 containers:
  - name: nginx-containers
    image: nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
